// Generated by `bun run generate` from packages/assets/images. Do not edit.
import type { AssetEntry } from "./config.ts";

/** Every image under `images/`, keyed by its path relative to that directory. */
export const ASSET_MANIFEST = {} as const satisfies Readonly<Record<string, AssetEntry>>;

/** Every path present in {@link ASSET_MANIFEST}; `never` while it is empty. */
export type AssetPath = keyof typeof ASSET_MANIFEST;
