import { recommended } from "@effect/tsgo/oxlint-presets";
import { defineConfig } from "vite-plus";

const ignorePatterns = [
    "**/node_modules/**",
    "**/dist/**",
    "**/build/**",
    "**/.output/**",
    "**/.alchemy/**",
    "**/.wrangler/**",
    "**/.tanstack/**",
    "**/.nitro/**",
    "**/.astro/**",
    "**/.convex/**",
    "**/_generated/**",
    "**/*.gen.ts",
    "packages/backend/convex/**",
    "packages/backend/AGENTS.md",
    "packages/backend/CLAUDE.md",
    "packages/backend/.agents/**",
    "packages/backend/.claude/**",
    "packages/backend/skills-lock.json",
    "bun.lock",
    "tools/oxlint/**",
];

export default defineConfig({
    run: { cache: true },
    test: { passWithNoTests: true },
    lint: {
        extends: [recommended],
        options: { typeAware: true, typeCheck: true },
        jsPlugins: [
            { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
            { name: "effect", specifier: "./tools/oxlint/effect/index.ts" },
        ],
        rules: {
            "anti-slop/no-chained-type-assertions": "error",
            "anti-slop/no-conditional-empty-object-spread": "error",
            "anti-slop/no-known-value-widening": "error",
            "anti-slop/no-module-mocking": "error",
            "anti-slop/no-object-parameters": "error",
            "anti-slop/no-reflect-apply": "error",
            "anti-slop/no-reflect-get": "error",
            "anti-slop/no-runtime-typeof": "error",
            "anti-slop/no-shape-in-symbol-names": "error",
            "anti-slop/no-unknown-parameters": "error",
            "anti-slop/no-unknown-returns": "error",
            "anti-slop/no-unknown-type-aliases": "error",
            "anti-slop/no-unsafe-dictionary-type": "error",
            "anti-slop/no-widen-then-assert": "error",
            "anti-slop/require-safety-comment-for-type-assertion": "error",
            "effect/no-cascading-layer-provide": "error",
            "effect/no-direct-fetch": "error",
            "effect/no-disable-validation": "error",
            "effect/no-effect-asvoid": "error",
            "effect/no-nested-effect-array-methods": "error",
            "effect/no-nested-layer-provide": "error",
            "effect/no-service-option": "error",
            "effect/no-shadowed-standard-array-static": "error",
            "effect/no-silent-error-swallow": "error",
            "effect/no-static-effect-service-forwarders": "error",
            "effect/pipe-max-arguments": "error",
            "effect/prefer-effect-match": "error",
            "effect/prefer-option-from-nullable": "error",
            "effect/require-context-service-in-services": "error",
        },
        ignorePatterns,
    },
    fmt: {
        printWidth: 100,
        tabWidth: 4,
        semi: true,
        singleQuote: false,
        sortPackageJson: false,
        overrides: [{ files: ["**/*.md"], options: { printWidth: 80, proseWrap: "always" } }],
        ignorePatterns,
    },
});
