/**
 * Regenerates `src/manifest.gen.ts` from the images under `images/`.
 *
 *   bun run generate     # rewrite the manifest
 *   bun run verify       # fail if the manifest is stale, without rewriting it
 */
import { collectAssets, type CollectedAsset } from "../src/sources.ts";

const OUTPUT = Bun.fileURLToPath(new URL("../src/manifest.gen.ts", import.meta.url));

const HEADER = [
    "// Generated by `bun run generate` from packages/assets/images. Do not edit.",
    'import type { AssetEntry } from "./config.ts";',
    "",
    "/** Every image under `images/`, keyed by its path relative to that directory. */",
].join("\n");

const FOOTER = [
    "",
    "/** Every path present in {@link ASSET_MANIFEST}; `never` while it is empty. */",
    "export type AssetPath = keyof typeof ASSET_MANIFEST;",
    "",
].join("\n");

function quote(value: string): string {
    return JSON.stringify(value);
}

function manifestSource(assets: readonly CollectedAsset[]): string {
    const entries = assets.map((asset) =>
        [
            `    ${quote(asset.path)}: {`,
            `        path: ${quote(asset.path)},`,
            `        key: ${quote(asset.key)},`,
            `        contentType: ${quote(asset.contentType)},`,
            `        width: ${asset.width},`,
            `        height: ${asset.height},`,
            `        bytes: ${asset.bytes},`,
            "    },",
        ].join("\n"),
    );
    // An empty object stays on one line so the committed file is format-stable.
    const literal = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;
    const declaration = `export const ASSET_MANIFEST = ${literal} as const satisfies Readonly<Record<string, AssetEntry>>;`;
    return `${HEADER}\n${declaration}\n${FOOTER}`;
}

const assets = await collectAssets();
const source = manifestSource(assets);
if (process.argv.includes("--check")) {
    const file = Bun.file(OUTPUT);
    if (!(await file.exists()) || (await file.text()) !== source) {
        throw new Error("Asset manifest is stale; run `bun run generate` in packages/assets.");
    }
    console.log(`verified ${assets.length} asset(s)`);
} else {
    await Bun.write(OUTPUT, source);
    console.log(`generated src/manifest.gen.ts with ${assets.length} asset(s)`);
}
