import { recommended } from "@effect/tsgo/oxlint-presets";
import { defineConfig } from "oxlint";

export default defineConfig({
    extends: [recommended],
    jsPlugins: [
        {
            name: "anti-slop",
            specifier: "./tools/oxlint/anti-slop/index.ts",
        },
        {
            name: "effect",
            specifier: "./tools/oxlint/effect/index.ts",
        },
    ],
    rules: {
        "anti-slop/no-chained-type-assertions": "error",
        "anti-slop/no-conditional-empty-object-spread": "error",
        "anti-slop/no-known-value-widening": "error",
        "anti-slop/no-module-mocking": "error",
        "anti-slop/no-object-parameters": "error",
        "anti-slop/no-reflect-apply": "error",
        "anti-slop/no-reflect-get": "error",
        "anti-slop/no-runtime-typeof": "error",
        "anti-slop/no-shape-in-symbol-names": "error",
        "anti-slop/no-unknown-parameters": "error",
        "anti-slop/no-unknown-returns": "error",
        "anti-slop/no-unknown-type-aliases": "error",
        "anti-slop/no-unsafe-dictionary-type": "error",
        "anti-slop/no-widen-then-assert": "error",
        "anti-slop/require-safety-comment-for-type-assertion": "error",
        "effect/no-cascading-layer-provide": "error",
        "effect/no-direct-fetch": "error",
        "effect/no-disable-validation": "error",
        "effect/no-effect-asvoid": "error",
        "effect/no-nested-effect-array-methods": "error",
        "effect/no-nested-layer-provide": "error",
        "effect/no-service-option": "error",
        "effect/no-shadowed-standard-array-static": "error",
        "effect/no-silent-error-swallow": "error",
        "effect/no-static-effect-service-forwarders": "error",
        "effect/pipe-max-arguments": "error",
        "effect/prefer-effect-match": "error",
        "effect/prefer-option-from-nullable": "error",
        "effect/require-context-service-in-services": "error",
    },
    ignorePatterns: [
        "node_modules/**",
        "dist/**",
        "lib/**",
        ".tmp/**",
        ".turbo/**",
        "out-tsc/**",
        ".alchemy/**",
        ".wrangler/**",
        ".dev.vars",
        ".env",
        ".env.local",
        "bun.lock",
        "tools/oxlint/**",
        ".expo/**",
        ".expo-shared/**",
        "web-build/**",
        "android/**",
        "ios/**",
        "apps/*/dist/**",
        "apps/*/lib/**",
        "apps/*/.expo/**",
        "apps/*/.alchemy/**",
        "apps/*/.agents/**",
        "apps/*/.wrangler/**",
        "apps/*/android/**",
        "apps/*/ios/**",
        "packages/*/.agents/**",
    ],
});
