import { defineConfig } from "oxlint";

export default defineConfig({
    options: {
        typeAware: true,
    },
    jsPlugins: [
        {
            name: "anti-slop",
            specifier: "./tools/oxlint/anti-slop/index.ts",
        },
    ],
    rules: {
        "anti-slop/no-chained-type-assertions": "error",
        "anti-slop/no-conditional-empty-object-spread": "error",
        "anti-slop/no-known-value-widening": "error",
        "anti-slop/no-module-mocking": "error",
        "anti-slop/no-object-parameters": "error",
        "anti-slop/no-reflect-apply": "error",
        "anti-slop/no-reflect-get": "error",
        "anti-slop/no-runtime-typeof": "error",
        "anti-slop/no-shape-in-symbol-names": "error",
        "anti-slop/no-unknown-parameters": "error",
        "anti-slop/no-unknown-returns": "error",
        "anti-slop/no-unknown-type-aliases": "error",
        "anti-slop/no-unsafe-dictionary-type": "error",
        "anti-slop/no-widen-then-assert": "error",
        "anti-slop/require-safety-comment-for-type-assertion": "error",
    },
    ignorePatterns: [
        "node_modules/**",
        "dist/**",
        "lib/**",
        ".tmp/**",
        ".turbo/**",
        "out-tsc/**",
        ".alchemy/**",
        ".wrangler/**",
        ".dev.vars",
        ".env",
        ".env.local",
        "bun.lock",
        "tools/oxlint/**",
        ".expo/**",
        ".expo-shared/**",
        "web-build/**",
        "android/**",
        "ios/**",
        "apps/*/dist/**",
        "apps/*/lib/**",
        "apps/*/.expo/**",
        "apps/*/.alchemy/**",
        "apps/*/.agents/**",
        "apps/*/.wrangler/**",
        "apps/*/android/**",
        "apps/*/ios/**",
        "packages/*/.agents/**",
    ],
});
